spring:
  config:
      import: optional:file:.env[.properties]

  application:
    name: wallet-service
  
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      "[hibernate.format_sql]": true

  flyway:
    enabled: true
  
server:
  port: ${SERVER_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health
