spring:
  application:
    name: wallet-service
  
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      "[hibernate.format_sql]": true

  flyway:
    enabled: true
  
server:
  port: ${SERVER_PORT}
